server:
  port: 9000

spring:
  application:
    name: "config"
  cloud:
    config:
      server:
        git:
          uri: "file:///home/darek/Devel/Spring/spring-io-lab18-config"
#          uri: "https://github.com/kaczynskid/spring-io-lab18-config.git"
#          uri: "git@github.com:kaczynskid/spring-io-lab18-config.git"

management:
  endpoints:
    web:
      base-path: "/admin"
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "always"
