management:
  metrics:
    export:
      jmx:
        enabled: true
      graphite:
        enabled: true
        host: "localhost"
        port: 2003
        protocol: "plaintext"
        step: "5s"
