spring:
  datasource:
    url: "jdbc:postgresql://${POSTGRES_PORT_5432_TCP_ADDR:localhost}:${POSTGRES_PORT_5432_TCP_PORT:5432}/${POSTGRES_DB:warehouse}"
    username: "${POSTGRES_USER:postgres}"
    password: "${POSTGRES_PASSWORD:sprio}"
  jpa:
    hibernate:
      ddl-auto: "validate"

management:
  server:
    port: 8081
  endpoints:
    web:
      base-path: "/admin"
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      jmx:
        enabled: true
      graphite:
        enabled: true
        host: "localhost"
        port: 2003
        protocol: "plaintext"
        step: "5s"
