spring:
  cloud:
    stream:
      bindings:
        stockUpdate:
          destination: "item-stock-update"
          content-type: "application/json"
          group: "warehouse"
          max-attempts: 3
      rabbit:
        bindings:
          stockUpdate:
            consumer:
              requeue-rejected: true
              auto-bind-dlq: true
              republish-to-dlq: true
